config/routes.rb
Negotiations::Application.routes.draw do

	resources :users do
		member do
			get 'toggle_admin'
			post 'last_seen'
			post 'accept_consent'
		end
	end

	resources :negotiations, only: [:new, :create]

	resources :scenarios, only: [:new, :create, :edit, :update]

	resources :sessions, only: [:new, :create, :destroy] # Reverse?

	root :to => 'static#home'

  get "static/home"

  get "static/search"

  get "static/reference"

	get 'users/index'

	get 'negotiations', to: 'negotiations#index'

	get 'convert', to: 'users#convert'

  get "static/about"

	post 'create_message', to: 'messages#create'

	post 'misc_negotiation', to: 'users#misc_negotiation'

	post 'agree_channel', to: 'users#agree_channel' ## Delete
	post 'finish_agreement', to: 'users#finish_agreement'

	get 'negotiations/messages'
	post 'users/accept_background'
	post 'users/alert_request'
	post 'users/accept_alert_request'
	post 'users/add_goal'
	post 'users/remove_goal'

	get 'javascript/coffeescript', to: 'javascript#coffee'
	get 'javascript/messages', to: 'javascript#messages'

	get 'rake_subject_numbers', to: 'users#rake_subject_numbers'

	match 'secure_key', to: 'negotiations#secure_key_validation'
	match 'reference', to: 'static#reference'
	match 'about', to: 'static#about'
	post 'signup', to: 'users#new'
	match 'log_in', to: 'sessions#new'
	match 'log_out', to: 'sessions#destroy'
	match 'consent', to: 'users#consent'
	match 'background', to: 'users#background'
	match 'instructions', to: 'users#instructions'
	match 'waiting', to: 'users#waiting'
	match 'agreement', to: 'users#agreement'
	match 'thank_you', to: 'users#thank_you'

	match 'hebrew', to: 'sessions#hebrew'
	match 'english', to: 'sessions#english'
	match 'he', to: 'sessions#hebrew'
	match 'en', to: 'sessions#english'

	match 'admin/:id' => 'tabs#admin'
	match 'background/:id' => 'tabs#background'
	match 'negotiation/:id' => 'tabs#negotiation'
	match 'supervisor/:id' => 'tabs#supervisor'

	get 'tabs/private_pub_subscribe'
	get 'tabs/private_pub_subscribe_admin'
	get 'tabs/waiting'
	get 'tabs/agree'

	match 'destroy/:id' => 'users#delete'
	match 'negotiations/destroy/:id' => 'negotiations#delete'
	match 'scenarios/destroy/:id' => 'scenarios#delete'
	match 'inspect/:id' => 'negotiations#inspect'

end

app/views/partials/_consent_form.html.erb
<div id = 'consent_form'>

  <h3><%= t('Consent') %><br />
  <strong><%= t("UofC") %></strong></h3>

<div id = 'scroll_consent'>

<p>
  You are invited to <strong>participate in a research study</strong> involving language and decision-making. You will be further briefed on the nature of the experiment after you have completed the study. 
</p>
<p>
  <span>Benefits.</span> The benefits of participating in this study include the opportunity to contribute to empirical research. 
</p>
<p>
  <span>Compensation and duration.</span> You will receive $10.00. The experiment should last a total of no more than 45 minutes. 
</p>
<p>
  <span>Risks.</span> There are minimal foreseeable physical or emotional risks involved. 
</p>
<p>
  <span>Confidentiality.</span> Your data will be recorded, analyzed, and kept on file for the sake of possible future analysis, but they will be kept completely confidential. We will maintain confidentiality by keeping your data under lock, and by separating your identity from the data when coding and analyzing them so that others will not be able to connect you with your data. 
</p>
<p>
  <span>Taping and recording.</span> In some cases we video or audio record participants as they perform the task. If we do, you will be informed. We might present clippings of these tapes for illustrative purposes. In these cases, your anonymity will be maintained, as we will not associate any personal information with the tapes presented. We ask for your permission to present these tapes at scientific settings. If we present clips in scientific settings, they will never reveal your identity. They will either not include your image, or will have the image from the back which will allow no such identification. 

  </p>

<p>
  <span>Your rights.</span> <strong>Your participation is voluntary and you have the right to withdraw your consent or discontinue participation at any time without penalty.</strong> You have the right to refuse to answer particular questions or perform any task. If <strong>for any reason</strong> you do not complete the experiment, you will still be compensated in proportion to the time you spent on the experiment. In addition, your privacy will be maintained in all published and written data resulting from this study. 
</p>
<p>
  <span>Questions or concerns.</span> If you have any questions regarding this study please contact the PI, Boaz Keysar at 773 702-5830, 5848 S. University Ave./Beecher 213, Chicago IL, 60637, or via e-mail at: <a href='mailto:boaz@uchicago.edu'>boaz@uchicago.edu</a> <br />
  If you have any concerns or are dissatisfied at any time with any aspect of this study, you may report your grievances -- anonymously, if you wish -- to the Social and Behavioral IRB Office. 
</p>
<p class = 'indented'>
  Social and Behavioral IRB Office 
  5835 S. Kimbark Avenue, Judd Hall 333 
  Chicago, IL 60637 
  773-834-7835; <a href='mailto:sbs-irb@uchicago.edu'>sbs-irb@uchicago.edu</a>
</p>

<p>
  Clicking on “Accept” and/or submitting the completed survey will be taken as your consent to participate in this study.
  </p>
  <p class ='centered_button'>
  <input type = 'submit' class = 'consent_button' value = <%= t('accept') %> ></p>
</div>

</div>

app/views/partials/_goals.erb
<ul>
  <li>Goals Met (Hover)</li>
  <% current_user.goals.each do |goal| %>
    <li>
      <input type="checkbox" id="<%= goal[0].gsub(/\s/, '_').downcase %>" <%= current_user.chosen_goals_or_string.split(' ').include?(goal[0].split(' ').join('_').downcase) ? "checked" : "" %> >
      <label for="<%= goal[0].gsub(/\s/, '_').downcase %>"><%= goal[0].capitalize %> — <%= goal[1] %></label>
    </li>
  <% end %>
</ul>

app/views/partials/_instructions.erb
<div id = 'instructions'>

  <h2><%= t('Followme') %>:</h2>

  <p>In this study, you will be asked to
    negotiate with another person in
    <%= current_user.scenario.language %>.<new>You will meet
    the other participant at the end of the study.</new></p>

 <p>After agreeing to the consent form, the background page
    will give you all the information you need. Do not continue
    past the background until you are prepared to negotiate.</p>

  <p><!-- You have 30 minutes to negotiate to an agreement.
    You do not need to take all 30 minutes.  -->You will be able to
    read the background while negotiating. To move on to the
    agreement form, scroll to the end of the background section
    and click "Fill out Form".

    <new>You may find that reaching an agreement is difficult
      without some creative problem solving. There is a solution
      that meets everyone's needs. Approximately 50% of participants
      come to the solution.</new>

    If you cannot reach an agreement,
    please try to explain why.</p>

  <p>Try to refer to yourself and to the opposite party using
    plural or gender-neutral terms, without using names.</p>

  <p>Speak exclusively in <%= current_user.scenario.language %>.</p>


</div>

app/views/partials/_negotiation_table.html.erb
<h2>Negotiations</h2>

<div class =  'table_scroll'>
<table class = 'negotiation_table'>
  
  <tr id = 'entry_definitions'>
    <td>ID</td>
    <td>Scenario</td>
    <td>Secure Key</td>
    <td>Users</td>
  </tr>
  
  <% Negotiation.all.each do |neg| %>
    <tr class = 'negotiation_entry table_entry' data-id = '<%= neg.id %>' data-user-id = "<%=j list_user_id(neg) %>" 
      data-scenario-id = "<%= neg.scenario.id %>" >
      <td><%= neg.id %></td>
      <td class = 'name_entry'><%= neg.scenario.title %></td>
      <td><%= neg.secure_key %></td>
      <td><%= "#{neg.users.count}/2" %></td>
    </tr>
  <% end %>
  
</table>
</div>

<a href = '/negotiations/new'>
<%= button_tag 'New', class: 'new_neg_button' %>
</a>


<%= button_tag 'Inspect', class: 'inspect_neg_button' %>

<%= button_tag 'Delete', class: 'delete_neg_button' %>

app/views/partials/_scenario_table.html.erb
<h2>Scenarios</h2>

<div class =  'table_scroll'>
<table class = 'scenario_table'>
  
  <tr id = 'entry_definitions'>
    <td>ID</td>
    <td>Title</td>
    <td>Language</td>
  </tr>
  
  <% Scenario.all.each do |scenario| %>
    <tr class = 'scenario_entry table_entry' data-id = '<%= scenario.id %>' >
      <td><%= scenario.id %></td>
      <td class = 'name_entry'><%= scenario.title %></td>
      <td><%= scenario.language.capitalize %></td>
    </tr>
  <% end %>
  
</table>
</div>

<a href = '<%= new_scenario_path %>'>
<%= button_tag 'New' %>
</a>

<%= button_tag 'Edit', class: 'edit_scenario_button' %>

<%= button_tag 'Delete', class: 'delete_scenario_button' %>

app/views/partials/_user_table.html.erb
<h2>Users</h2>

<div class =  'table_scroll'>
<table class = 'user_table'>
  
  <tr id = 'entry_definitions'>
    <td>Subject Number</td>
    <td>Name</td>
    <td>Secure Key</td>
    <td>Online</td>
    <td>Admin</td>
  </tr>
  
  <%= render User.all %>
  
</table>
</div>

<%= button_tag 'Make Admin', class: 'admin_button' %>

<%= button_tag 'Delete', class: 'delete_button' %>