config/routes.rb
Negotiations::Application.routes.draw do

	resources :users do
		member do
			get 'toggle_admin'
			post 'last_seen'
			post 'accept_consent'
		end
	end

	resources :negotiations, only: [:new, :create]

	resources :scenarios, only: [:new, :create, :edit, :update]

	resources :sessions, only: [:new, :create, :destroy] # Reverse?

	root :to => 'static#home'

  get "static/home"

  get "static/search"

  get "static/reference"

	get 'users/index'

	get 'negotiations', to: 'negotiations#index'

	get 'convert', to: 'users#convert'

  get "static/about"

	post 'create_message', to: 'messages#create'

	post 'misc_negotiation', to: 'users#misc_negotiation'

	post 'agree_channel', to: 'users#agree_channel' ## Delete
	post 'finish_agreement', to: 'users#finish_agreement'

	get 'negotiations/messages'
	post 'users/accept_background'
	post 'users/alert_request'
	post 'users/accept_alert_request'
	post 'users/add_goal'
	post 'users/remove_goal'

	get 'javascript/coffeescript', to: 'javascript#coffee'
	get 'javascript/messages', to: 'javascript#messages'

	get 'rake_subject_numbers', to: 'users#rake_subject_numbers'

	match 'secure_key', to: 'negotiations#secure_key_validation'
	match 'reference', to: 'static#reference'
	match 'about', to: 'static#about'
	post 'signup', to: 'users#new'
	match 'log_in', to: 'sessions#new'
	match 'log_out', to: 'sessions#destroy'
	match 'consent', to: 'users#consent'
	match 'background', to: 'users#background'
	match 'instructions', to: 'users#instructions'
	match 'waiting', to: 'users#waiting'
	match 'agreement', to: 'users#agreement'
	match 'thank_you', to: 'users#thank_you'

	match 'hebrew', to: 'sessions#hebrew'
	match 'english', to: 'sessions#english'
	match 'he', to: 'sessions#hebrew'
	match 'en', to: 'sessions#english'

	match 'admin/:id' => 'tabs#admin'
	match 'background/:id' => 'tabs#background'
	match 'negotiation/:id' => 'tabs#negotiation'
	match 'supervisor/:id' => 'tabs#supervisor'

	get 'tabs/private_pub_subscribe'
	get 'tabs/private_pub_subscribe_admin'
	get 'tabs/waiting'
	get 'tabs/agree'

	match 'destroy/:id' => 'users#delete'
	match 'negotiations/destroy/:id' => 'negotiations#delete'
	match 'scenarios/destroy/:id' => 'scenarios#delete'
	match 'inspect/:id' => 'negotiations#inspect'

end

app/controllers/users_controller.rb
require 'csv'

class UsersController < ApplicationController

	before_filter :get_locale
	before_filter :signed_in_user, except: [:new, :create]
	before_filter :correct_user, only: [:show, :edit, :update, :accept_consent]
	before_filter :admin_user, only: [:toggle_admin, :delete, :index, :rake_subject_numbers]
	layout false, only: :index


	def new
		if signed_in?
			flash[:error] = "You are already logged into an account."
			redirect_to root_url
		else
			if @neg = Negotiation.find_by_secure_key(params[:secure_key])
				check_set_locale(@neg.scenario.language)
				unless @neg.full?
					@secure_key = params[:secure_key]
					@title = 'Sign Up'
					@page_id = 'sign_up'
					@user = User.new()
				else
					flash[:error] = 'That secure key has already been used.'
					redirect_to secure_key_url
				end
			else
				flash[:error] = 'You do not have a valid secure key'
				redirect_to secure_key_url
			end
		end
 	end

	def show
		redirect_to root_url
	end

	def convert
		respond_to do |format|
			format.csv {
				csv_string = CSV.generate do |csv|
					csv << ['Subject Number', 'Name', 'E-Mail']
					csv << ['-----------------', '-----------------', '-----------------']
					User.all.each do |user|
						unless user.admin
							csv << [user.subject_number, user.name, user.email]
						end
					end
				end
				render inline: csv_string
			}
		end
	end

	def rake_subject_numbers
		@users = User.all
		@users.sort_by! { |user| user.created_at }
		@users.reject! { |user| user.admin }
		@users.each_with_index do |user, i|
			user.update_attribute :subject_number, (i + 1)
			puts "#{user.name}: subject number : #{i + 1}"
		end
		redirect_to root_url
	end

	def index
		respond_to do |format|
			format.csv {
				csv_string = CSV.generate do |csv|
					csv << User.array_header
					csv << User.array_spacer
					User.all.each do |user|
						unless user.admin
							csv << user.make_array
						end
					end
				end
				render inline: csv_string
			}
		end
	end

	def add_goal
		user = current_user
		goals = user.chosen_goals || ''
		goals = goals.split ' '
		goals << params[:goal] unless goals.include? params[:goal]
		# Might destroy password...
		current_user.update_attribute :chosen_goals, (goals.join ' ')
		sign_in user # Very Important
		render inline: 'Done'
	end

	def remove_goal
		user = current_user
		goals = user.chosen_goals || ''
		goals = goals.split ' '
		goals.delete params[:goal]
		# Might destroy password...
		current_user.update_attribute :chosen_goals, (goals.join ' ')
		sign_in user # Very Important
		render inline: 'Done'
	end

	def create
		@secure_key = params[:user][:secure_key]
		@user = User.new(params[:user])
		@user.native_languages =
			params[:user][:native_languages].gsub(/\s/, '').downcase.split(',')
		@user.foreign_languages =
			params[:user][:foreign_languages].gsub(/\s/, '').downcase.split(',')


		if @neg = Negotiation.find_by_secure_key(@user.secure_key)
			unless @neg.full?
				if @user.save
					sign_in @user
					flash[:success] = 'Welcome'
					redirect_to instructions_url
				else
					@title = 'Sign Up'
					@page_id = "sign_up"
					render 'new'
				end
			else
				@title = 'Sign Up'
				@page_id = 'sign_up'
				flash.now[:error] = 'That secure key has already been used.'
				render 'new'
			end
		else
			@title = 'Sign Up'
			@page_id = "sign_up"
			flash.now[:error] = 'You do not have a valid secure key'
			render 'new'
		end

	end

	def last_seen
		$redis.set "#{current_user.id}_last_seen", Time.now.to_i if current_user
		render inline: 'Done'
	end

	def accept_consent
		@user = User.find(params[:id])
		@user.update_attribute(:start_background, Time.now) unless @user.start_background
		@user.update_attribute(:consent, true)
		sign_in @user # Very important, update attributes changes.
		render inline: "Done"
	end

	def accept_background
		PrivatePub.publish_to "/negotiation/waiting/#{current_user.negotiation.id}", :content => true
		@user = current_user
		@user.update_attribute(:end_background, Time.now) unless @user.end_background
		@user.update_attribute(:background, true)
		if @user.negotiation.user_background?
			@user.negotiation.update_attribute :start_time, Time.now unless @user.negotiation.start_time
		end
		sign_in @user
		redirect_to root_url
	end

	def alert_request
		PrivatePub.publish_to "/negotiation/#{current_user.negotiation.id}/new",
			alert_request: true,
			sender_id: current_user.id
		render inline: 'Done'
	end

	def misc_negotiation
		PrivatePub.publish_to "/negotiation/#{current_user.negotiation.id}/new", params
		render inline: 'Done'
	end

	def accept_alert_request
		if params[:tactic] == 'accept'

			@negotiation = current_user.negotiation

			@negotiation.end_time = Time.now
			@negotiation.save!

			@negotiation.users.each do |user|
				user.make_agree
			end

			# Has to be before the publish, because otherwise
			# publish could take users to page before page is
			# accessible.

			PrivatePub.publish_to "/negotiation/#{current_user.negotiation.id}/new",
				accept_alert_request: true

			render inline: 'Done'
		else
			PrivatePub.publish_to "/negotiation/#{current_user.negotiation.id}/new",
				deny_alert_request: true,
				sender_id: current_user.id
			render inline: 'Done'
		end
	end

	def agreement
		if current_user.negotiation.agreed?
			@title = 'Agreement'
			@page_id = 'agreement_page'
			@body_id = 'user_show' # For no scrolling
		else
			redirect_to root_url
		end
	end

	def consent
		current_user.set_role_if_not_yet_set
		@title = 'Consent'
		@page_id = 'consent_page'
	end

	def agree_channel
		PrivatePub.publish_to "/#{current_user.negotiation.id}/agree", params

		render inline: 'Done'
	end

	def finish_agreement

 		@agreement = current_user.agreement
 		@negotiation = current_user.negotiation
 		@agreement.agreement_boolean = params[:agreement_boolean]
 		@agreement.price = params[:price]
 		@agreement.description = params[:description]
 		@agreement.save!

 		@negotiation.record_agreement_time unless @negotiation.agreement_time

 		render inline: 'Done'
 	end

	# def finish_agreement
	# 	price = params[:price]
	# 	if price
	# 		if price =~ /\A[+-]?[0-9]*\.?[0-9]+\Z/ && Float(price) <= 500000
	# 			valid = true
	# 		else
	# 			valid = true
	# 		end
	# 	else
	# 		valid = true
	# 	end
	# 	if valid
	# 		@agreement = current_user.agreement
	# 		@negotiation = current_user.negotiation
	# 		@agreement.agreement_boolean = params[:agreement_boolean]
	# 		@agreement.price = params[:price]
	# 		@agreement.description = params[:description]
	# 		@agreement.save!
	#
	# 		@negotiation.record_agreement_time unless @negotiation.agreement_time
	#
	# 		render inline: 'Done'
	# 	else
	# 		PrivatePub.publish_to "/#{current_user.negotiation.id}/agree", tactic: 'not_done'
	# 		render inline: 'Not done'
	# 	end
	# end

	def thank_you
		if current_user.negotiation.thank_you?
			@title = 'Thank You!'
			@page_id = 'thank_you_page'
		else
			redirect_to root_url
		end
	end

	def background
		@title = 'Background'
		@page_id = 'background_page'
	end

	def waiting
		@title = 'Waiting'
		@page_id = 'waiting_page'
	end

	def instructions
		@title = 'Instructions'
		@page_id = 'instructions_page'
	end

	def edit
		@title = 'Settings'
		@page_id = 'settings'
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		# @attributes = params[:user]
		# @attributes[:secure_key] = @user.secure_key
		#
		# @attributes[:native_languages] =
		# 	params[:user][:native_languages].gsub(/ /, '').downcase.split(',')
		# @attributes[:foreign_languages] =
		# 	params[:user][:foreign_languages].gsub(/ /, '').downcase.split(',')
		@attributes = params[:user]

		@user.password = @attributes[:new_password]
		@user.password_confirmation = @attributes[:password_confirmation]
		@user.name = @attributes[:name]
		@user.email = @attributes[:email]

		if @user.save

			flash[:success] = 'You have succcessfully updated your settings.'
			sign_in @user
			redirect_to root_url

		else
			@title = 'Settings'
			@page_id = 'settings'
			render 'edit'
		end

	end

	def delete
		User.find(params[:id]).destroy
		render inline: 'Done'
	end

	def toggle_admin
		@user = User.find(params[:id])
		if @user.admin
			@user.update_attribute(:admin, false)
		else
			@user.update_attribute(:admin, true)
		end
		render inline: 'Done'
	end

	private

		def signed_in_user
			if signed_in?
				@neg = current_user.negotiation
				if @neg
					@lang = @neg.scenario.language
					check_set_locale @lang
				end
			else
				store_location
				redirect_to log_in_url
				flash[:error] = 'Please Sign In'
			end
		end

		def admin_user
			unless current_user.admin
				redirect_to root_url
				flash[:error] = 'You do not have permission to access that page.'
			end
		end

		def correct_user
			@user = User.find(params[:id])
			unless current_user?(@user)
				redirect_to root_url
				flash[:error] = 'You do not have permission to access that page.'
			end
		end

		def get_locale
			I18n.locale = cookies[:locale] || I18n.default_locale
		end

end

app/helpers/users_helper.rb
module UsersHelper

	def first_user?(user)
		user == user.negotiation.first_user
	end
	
	def language_string(array)
		out = ''
		array.each do |item|
			out << item.capitalize << ', '
		end
		out.gsub /, $/, ''
	end
	
	def online_users 
		online = []
		$redis.keys.each do |key|
			if key =~ /_last_seen$/
				user = User.find(key.sub(/_last_seen$/, ''))
				online << user if user.online?
			end
		end
		online
	end
	
	def online_admin
		admin = []
		online_users.each do |user|
			admin << user if user.admin
		end
		admin
	end
	
	def set_locale(locale)
		cookies[:locale] = locale
		I18n.locale = cookies[:locale]
	end
	
	def check_set_locale(locale)
		if locale =~ /english/i
			set_locale('en')
		elsif locale =~ /hebrew/i
			set_locale('he')
		end
	end
	
end

app/views/users/_user.html.erb
   
   
    <% unless user == current_user %>
    <tr class = 'user_entry table_entry' data-user-id = '<%= user.id %>' data-admin = '<%= user.admin %>' data-negotiation-id = "<%= user.negotiation.id if user.negotiation %>" >
      <td><%= user.subject_number %></td>
      <td><%= user.name %></td>
      <td><%= user.secure_key %></td>
      <td><%= user.online? %></td>
      <td><%= user.admin %></td>
    </tr>
    <% end %>

app/views/users/agreement.html.erb
<%= subscribe_to "/#{current_user.negotiation.id}/agree"  %>
<%= javascript_include_tag '/tabs/agree.js' %>

<h1><%= t('Agreement') %></h1>

<div id = 'sender_page'>

	<h2><%= t('Yours') %></h2>

	<div class = 'basic_form'>
	<%= label_tag :agreement_boolean, t('Agreed') %>
	<%= select_tag :agreement_boolean, options_for_select([[nil, nil], [t('ofcourse'), true], [t('never'), false]]), class: 'agreement_boolean' %></div>

	<br />

	<div class = 'yes_form'>
		<div class = 'basic_form'>

			<%= label_tag :agreement_price, t('Sold') %>
			<%= number_field_tag :agreement_price, '', step: 25000 %><br /><br />

			<%= label_tag :agreement_content_yes, t('Extrapolaborate').html_safe %>
			<%= text_area_tag :agreement_content_yes %>

					<div id = 'agreement_goals'>
						<%= render 'partials/goals' %>
					</div>

			<%= button_tag t('Submit'), class: 'submit_yes' %>

		</div>
	</div>

	<div class = 'no_form'>
		<div class = 'basic_form'>

			<%= label_tag :agreement_content_no, t('Whydoyouhateeachother') %>
			<%= text_area_tag :agreement_content_no %>


				<div id = 'agreement_goals'>
					<%= render 'partials/goals' %>
				</div>

			<%= button_tag t('Submit'), class: 'submit_no' %>

		</div>
	</div>


</div>

<div id = 'receiver_page'>

	<h2><%= t('Partners') %></h2>

	<div class = 'basic_form'>
	<%= label_tag :agreement_boolean, t('Agreed') %>
	<%= select_tag :agreement_boolean, options_for_select([[nil, nil], [t('ofcourse'), true], [t('never'), false]]), class: 'agreement_boolean' %></div>

	<br />

	<div class = 'yes_form'>
		<div class = 'basic_form'>

			<%= label_tag :receiver_price, t('Sold') %>
			<%= number_field_tag :receiver_price, '', step: 25000 %><br /><br />

			<%= label_tag :receiver_content_yes, t('Extrapolaborate').html_safe %>
			<%= text_area_tag :receiver_content_yes %>


			<%= button_tag t('Submit'), class: 'receiver_yes' %>

		</div>
	</div>

	<div class = 'no_form'>
		<div class = 'basic_form'>

			<%= label_tag :receiver_content_no, t('Whydoyouhateeachother') + ':' %>
			<%= text_area_tag :receiver_content_no %>

			<%= button_tag t('Submit'), class: 'receiver_no' %>

		</div>
	</div>

	<div id = 'stop_receiver'></div>

</div>

<button id = 'alert_partner'><%= t('Alert4') %></button>
<div class = 'basic_form' id = 'alert_content_div'>
	<div>
		<h1><%= t('Alert1') %></h1>
		<input type = 'text' id = 'alert_content'>
		<!-- <%= text_area_tag 'alert_content', '', id: 'alert_content' %> -->
		<input type = 'submit' id = 'send_alert' value = <%= t('notbycarrierpigeon') %>
	</div>
</div>

app/views/users/background.html.erb
<%= render '/partials/tabs/background' %>

<div style = 'text-align:center'>
<%= form_tag users_accept_background_path do %>
<%= submit_tag t('ready'), class: 'basic_button background_button' %>
<% end %>
</div>

app/views/users/consent.html.erb
<%= render '/partials/consent_form' %>

app/views/users/edit.html.erb
<h1>Settings</h1>

<div id = 'sign_up_form' class = 'basic_form'>
	
	<%= form_for(@user) do |f| %>
		
		<%= render 'shared/error_messages' %>

<!--		<div><%= f.label :username %></div>
		<div><%= f.text_field :username,
			placeholder: 'johnsmith' %></div> -->
		
		<div><%= f.label :name %></div>
		<div><%= f.text_field :name, 
			placeholder: 'John Smith' %></div>

		<div><%= f.label :email %></div>
		<div><%= f.text_field :email %></div>
    
		<div><%= f.label :new_password %></div>
		<div><%= f.password_field :new_password %></div>
		
		<div><%= f.label :password_confirmation, 'Confirmation' %></div>
		<div id = 'last_input'><%= f.password_field :password_confirmation %></div>
		
<!--    <div id = 'wizard_page'>
      <div><%= f.label :date_of_birth %></div>
      <div><%= f.date_select :date_of_birth, start_year: Time.now.year - 60, end_year: Time.now.year - 18 %></div>

      <div><%= f.label :sex %></div>
      <div><%= f.select :sex,
        options_for_select([['Male', 'male'], ['Female', 'female']]) %></div>

      <div><%= f.label :native_languages %></div>
      <div class = 'language_array'><%= f.text_field :native_languages,
        value: language_string(current_user.native_languages), placeholder: 'Korean, English' %></div>

      <div><%= f.label :foreign_languages %></div>
      <div class = 'language_array'><%= f.text_field :foreign_languages, value: language_string(current_user.foreign_languages), placeholder: 'Spanish, German' %></div>


      <%= button_tag 'Back', class: 'back_button', style: 'font-size:15px;', type: 'button' %>

    </div> -->

    <%= f.submit "Submit", id: 'submit_button' %>
		
	<% end %>
  
<!--  <%= button_tag 'Next', class: 'next_button', style: 'font-size:15px;' %> -->
</div>

app/views/users/instructions.html.erb
<%= render '/partials/instructions' %>

<div style = 'text-align:center'>
<input type = 'submit' class = 'instructions_button basic_button' value = <%= t('Next') %> ></p>
</div>

app/views/users/show.html.erb
<% unless current_user.admin %>
	<%= subscribe_to "/negotiation/#{current_user.negotiation.id}/new" %>
	<%= javascript_include_tag '/tabs/private_pub_subscribe.js' %>
<% end %>
 <!-- Heres's the private_pub subscribe -->

<div id="tab-container" class="tab-container">
  <ul class='etabs' id = 'tabs_for_<%= current_user.id %>' data-id = '<%= current_user.id %>'>
    <% @tabs.each do |tab| %>
      <li class='tab_link' id = 'tab_link_<%= tab[:title].downcase %>' >
        <a href="#tab_<%= tab[:title].downcase %>"><%= tab[:heading] %></a>
      </li>
    <% end %>
  </ul>

  <% @tabs.each do |tab| %>
    <div id="tab_<%= tab[:title].downcase %>" class = 'tab'>
      <%= render "/partials/tabs/#{tab[:title].downcase}" %>
    </div>
  <% end %>
</div> 
 
 

app/views/users/thank_you.html.erb
<h1><%= t('TYVM') %></h1>

<p><%= t('TYVM2') %></p>

app/views/users/waiting.html.erb
<%= subscribe_to "/negotiation/waiting/#{current_user.negotiation.id}"  %>
<%= javascript_include_tag '/tabs/waiting.js' %>

<h1><%= t('wait') %></h1>

<p><%= t('wait2') %></p>