config/routes.rb
Negotiations::Application.routes.draw do

	resources :users do
		member do
			get 'toggle_admin'
			post 'last_seen'
			post 'accept_consent'
		end
	end

	resources :negotiations, only: [:new, :create]

	resources :scenarios, only: [:new, :create, :edit, :update]

	resources :sessions, only: [:new, :create, :destroy] # Reverse?

	root :to => 'static#home'

  get "static/home"

  get "static/search"

  get "static/reference"

	get 'users/index'

	get 'negotiations', to: 'negotiations#index'

	get 'convert', to: 'users#convert'

  get "static/about"

	post 'create_message', to: 'messages#create'

	post 'misc_negotiation', to: 'users#misc_negotiation'

	post 'agree_channel', to: 'users#agree_channel' ## Delete
	post 'finish_agreement', to: 'users#finish_agreement'

	get 'negotiations/messages'
	post 'users/accept_background'
	post 'users/alert_request'
	post 'users/accept_alert_request'
	post 'users/add_goal'
	post 'users/remove_goal'

	get 'javascript/coffeescript', to: 'javascript#coffee'
	get 'javascript/messages', to: 'javascript#messages'

	get 'rake_subject_numbers', to: 'users#rake_subject_numbers'

	match 'secure_key', to: 'negotiations#secure_key_validation'
	match 'reference', to: 'static#reference'
	match 'about', to: 'static#about'
	post 'signup', to: 'users#new'
	match 'log_in', to: 'sessions#new'
	match 'log_out', to: 'sessions#destroy'
	match 'consent', to: 'users#consent'
	match 'background', to: 'users#background'
	match 'instructions', to: 'users#instructions'
	match 'waiting', to: 'users#waiting'
	match 'agreement', to: 'users#agreement'
	match 'thank_you', to: 'users#thank_you'

	match 'hebrew', to: 'sessions#hebrew'
	match 'english', to: 'sessions#english'
	match 'he', to: 'sessions#hebrew'
	match 'en', to: 'sessions#english'

	match 'admin/:id' => 'tabs#admin'
	match 'background/:id' => 'tabs#background'
	match 'negotiation/:id' => 'tabs#negotiation'
	match 'supervisor/:id' => 'tabs#supervisor'

	get 'tabs/private_pub_subscribe'
	get 'tabs/private_pub_subscribe_admin'
	get 'tabs/waiting'
	get 'tabs/agree'

	match 'destroy/:id' => 'users#delete'
	match 'negotiations/destroy/:id' => 'negotiations#delete'
	match 'scenarios/destroy/:id' => 'scenarios#delete'
	match 'inspect/:id' => 'negotiations#inspect'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title><%= title_helper(@title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <%= javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery?%>
  
  <%= javascript_tag "var CURRENT_USER_ID = '#{current_user.id}';" if current_user %>
  
    <%= javascript_tag "var CURRENT_USER_NEGOTIATION_ID = '#{current_user.negotiation.id}';" if current_user && current_user.negotiation %>
  
  
  <!--
  /* @license
   * MyFonts Webfont Build ID 1316338, 2011-10-03T10:50:35-0400
   * 
   * The fonts listed in this notice are subject to the End User License
   * Agreement(s) entered into by the website owner. All other parties are 
   * explicitly restricted from using the Licensed Webfonts(s).
   * 
   * You may obtain a valid license at the URLs below.
   * 
   * Webfont: Proxima Nova Thin by Mark Simonson
   * URL: http://www.myfonts.com/fonts/marksimonson/proxima-nova/thin/
   * Licensed pageviews: 10,000,000
   * 
   * Webfont: Proxima Nova Regular by Mark Simonson
   * URL: http://www.myfonts.com/fonts/marksimonson/proxima-nova/regular/
   * Licensed pageviews: 10,000,000
   * 
   * Webfont: Proxima Nova Semibold by Mark Simonson
   * URL: http://www.myfonts.com/fonts/marksimonson/proxima-nova/semibold/
   * Licensed pageviews: 10,000,000
   * 
   * Webfont: Proxima Nova Light by Mark Simonson
   * URL: http://www.myfonts.com/fonts/marksimonson/proxima-nova/light/
   * Licensed pageviews: 10,000,000
   * 
   * Webfont: Proxima Nova Bold by Mark Simonson
   * URL: http://www.myfonts.com/fonts/marksimonson/proxima-nova/bold/
   * Licensed pageviews: 10,000,000
   * 
   * 
   * License: http://www.myfonts.com/viewlicense?type=web&buildid=1316338
   * Webfonts copyright: Copyright (c) Mark Simonson, 2005. All rights reserved.
   * 
   * © 2011 Bitstream Inc
  */
  -->
  <link rel="stylesheet" 
  href="//identity.uchicago.edu/c/fonts/proximanova.css">
  <%= javascript_include_tag "https://private-publish.herokuapp.com/faye.js" %>
  <%= javascript_include_tag "/private-pub-lib.js" %>
  
  <% if cookies[:locale] == 'he' %>
  	
	<style>
	@import url(http://fonts.googleapis.com/earlyaccess/alefhebrew.css);
		
/*	* {
		font-family: 'Alef Hebrew'
	} */
		
	p, input, div, textarea {
		text-align:right;
	}
	
	h1,h2,h3,h4,h5,h6 {
		text-align:center;
	}
	
	header h1 {
		text-align:right;
		left:-20px;
	}
	
	header nav {
		left:20px;
	}
	
	#home p {
		text-align:center;
	}
	
	#dot_slider {
		position:relative;
		text-align:left;
		transform: rotateY(180deg);
	}
	
	#wizard_page_3 div {
		text-align:left;
	}
	
	#wizard_page_4, #wizard_page_4 div {
		text-align:right;
	}
	
	#wizard_page_4 input[type='submit'], #wizard_page_4 button {
		float:right;
	}
	
	.dropdown {
		left:0px;
		top:15px;
	}
	
	.checkboxes input[type='checkbox'] {
		float:right;
	}
	
	.div_with_other input[type='checkbox'] {
		position:relative;
		top:13px;
	}
	
	.div_with_other .other_text {
		float:right;
		position:relative;
		top:14px;
	}
  		
	</style>
  <% end %>
</head>
<body id = "<%= @body_id %>" data-id = "<%= current_user.id if current_user %>">

	<header>
		
		<div id = 'line'></div>
		
		<h1>
			<%= link_to root_path do %>
			<div id = 'shield'></div>
			<span style = 'padding-left:14px'><%= t('nego').upcase() %></span>
			<% end %>
		</h1>
		
		<nav>
			<% if signed_in? %>
			<% unless current_user.admin %>
  			<li><%= link_to t('Followme'), instructions_path %></li>
			
			<% else %>
			  <li><%= link_to t('Followme'), '#' %></li>
			<% end %>
			<li class = 'dropdown_trigger'><%= link_to t('account'), '#' %></li>
			<ul class = 'dropdown'>
				<!-- <li><%= link_to 'Profile', user_path(current_user) %></li> -->

				<li><%= link_to t('set'), edit_user_path(current_user) %>
        </li>
				<div class = 'divider'></div>
				<li><%= link_to t("Logout"), log_out_path, method: 'delete' %></li>
			</ul>
			<% else %>
			  <li><%= link_to t("Login"), log_in_path %></li>
        <li><%= link_to t('signup'), secure_key_path %></li>
      <% end %>
			<% unless signed_in? %>
			<% else %>
			<% end %>
		</nav>
		
	</header>
	
	<% flash.each do |key, value| %>
	<div class = "flash flash-<%= key %>">
		<%= value %>
	</div>
	<% end %>
	

	<section id = "<%= @page_id %>">

	<%= yield %>

	</section>

  	<!-- <%= debug(params) if Rails.env.development? %> -->

	<footer class = 'fixed_footer'>
		<div>
		
		<p><%= t('copy') %><p>

		</div>
	</footer>
	
	
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  
	<script src="/javascript/coffeescript.js"
	 type="text/javascript"></script>
	 
 	<script src="/javascript/messages.js"
 	 type="text/javascript"></script>
  
  
  <script src="/easytabs.js" type="text/javascript"></script>
  <script src="/expanding.js" type="text/javascript"></script>
  <script src="/autosize.js" type="text/javascript"></script>
  <script src="/spin.js" type="text/javascript"></script> 
</body>
</html>